In [32]:
import pandas as pd
import numpy as np
data = pd.read_csv("../HackathonMicrobiomeData/CAD/ClassCAD_train.csv")


#AT THE MOMENT THE FIRST COLOUMN CONTAINS LETTER SO REMOVE IT
#MAYBE THIS NEEDS TO BE CHANGED LATER

#THE FUNCTION CALCULATES A VALUE BETWEEN [0,1] FOR EVERY INDEPENDANT VARIABLE Xi, THE VALUE OF THE DEPENDANT VARIABLE Y IS NOT IN THE OUTPUT 
#THE INDEPENDANT VARIABLE SHOULD ALWAYS BE IN THE LAST COLLUMN!!!!
#FOR THE CALCULATION OF THE VALUE FOR EVERY VARIABLE Xi WHICH HAS A HIGH CORRELATION WITH ANOTHER VARIABLE Xj -
#THE FORUMULAR IS |corXiY| - |corXiXj|/weight
#SO MAKE SURE TO TAKE THE RIGHT WEIGHT

def correlationPValues(data, weight):
    data = data.values
    data = data.T[1:len(data)].T

    print(data)
    print(data.shape[0])
    for i in range(0, len(data)):
        if np.std(data[i]) == 0:
            print("Standardabweichung eines Attributs ist 0, Covarianz kann nicht bestimmt werden")

    covMatrix = np.cov(data.tolist())
    corMatrix = np.corrcoef(data.tolist())
    print(corMatrix)
    #get correlation from every independant variable with label
    correlationValues = corMatrix.T[data.shape[0] - 1]
    correlationWithLabel = corMatrix.T[data.shape[0] - 1]
    bestAttributes = []
    #add index of label to eliminatedAttributes
    eliminatedAttributes = [len(correlationValues)-1]

    variableToPValue = {}
    while(True):
        #get the highest correlation
        maxCor = -10
        bestAttribute = 0
        for i in range(0, len(correlationValues)):
            if i not in bestAttributes and i not in eliminatedAttributes:
                if correlationValues[i] > maxCor:
                    maxCor = correlationValues[i]
                    bestAttribute = i
        variableToPValue[bestAttribute] = maxCor     
        #Add best index to best attributes
        bestAttributes.append(bestAttribute)
        #get correlation from every independant variable with best Attribute
        correlationWithBestAttribute = corMatrix.T[bestAttribute]

        #iterate through correlation and eliminate every variable with cor >= 0.7
        count = 0
        for i in range(0, len(correlationWithBestAttribute)):
            if not(i in bestAttributes or i in eliminatedAttributes):
                if correlationWithBestAttribute[i] >= 0.7:
                    count = count + 1
                    eliminatedAttributes.append(i)
                    variableToPValue[i] = np.maximum(np.abs(correlationWithLabel[i]) - np.abs(correlationWithBestAttribute[i])/weight, 0)

        if(len(correlationValues) == len(eliminatedAttributes) + len(bestAttributes)):
            break;
    return variableToPValue


[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
572
[[1.         0.69703724 0.93990218 ... 0.96073711 0.98900549 0.63974843]
 [0.69703724 1.         0.88066635 ... 0.52151009 0.66564023 0.42840189]
 [0.93990218 0.88066635 1.         ... 0.81541942 0.90137477 0.53521765]
 ...
 [0.96073711 0.52151009 0.81541942 ... 1.         0.98307183 0.65373139]
 [0.98900549 0.66564023 0.90137477 ... 0.98307183 1.         0.66401105]
 [0.63974843 0.42840189 0.53521765 ... 0.65373139 0.66401105 1.        ]]
0.9987212830142578
0.5201845396012958
0.6549562910283737
0.581188294116706
0.6398735881903226
0.5128075142804176
0.5479328618791259
0.6596636424253406
0.6228096786666432
0.5873994790560043
0.515674567336156
0.6093490036091866
0.556926586177698
0.6490159537480759
0.6631194427189224
0.5021072330801799
0.5739676926521333
0.5091112198205083
0.6151866025715685
0.5452039216773352
0.6357824095836011
0.5861509082063112
0.546078254682377