In [58]:
import pandas as pd
import numpy as np



NameError: name 'calcFs' is not defined

In [49]:
np.linalg.svd(data, full_matrices= False)

(array([[-0.01720127,  0.00436441, -0.0231832 , ...,  0.02359994,
         -0.01423447,  0.00480673],
        [-0.00988842,  0.00264912, -0.00854788, ...,  0.02176669,
          0.01759964, -0.0277527 ],
        [-0.01295576,  0.00380358, -0.01614436, ..., -0.00885671,
          0.01367135,  0.00321949],
        ...,
        [-0.10014811,  0.06003979,  0.0036341 , ...,  0.00859011,
         -0.00308454,  0.00889006],
        [-0.00913769,  0.00254489, -0.00858944, ..., -0.00874034,
         -0.0116684 ,  0.00465052],
        [-0.14053648, -0.43837849,  0.13376027, ...,  0.01276685,
         -0.00270999,  0.02525031]]),
 array([54211.21001697, 37630.30281041, 32925.42815697, 28508.23966661,
        24926.51613505, 24014.52461199, 21783.03752366, 20075.26864147,
        16944.47121545, 16620.26728447, 15232.11802792, 14020.98025536,
        13915.93873431, 13442.68283294, 12923.1052007 , 12272.16565926,
        11355.15249731, 11245.54347697, 10811.40496151, 10611.23609024,
        10389

In [50]:
w

array([54211.21001697, 37630.30281041, 32925.42815697, 28508.23966661,
       24926.51613505, 24014.52461199, 21783.03752366, 20075.26864147,
       16944.47121545, 16620.26728447, 15232.11802792, 14020.98025536,
       13915.93873431, 13442.68283294, 12923.1052007 , 12272.16565926,
       11355.15249731, 11245.54347697, 10811.40496151, 10611.23609024,
       10389.23226158, 10334.43835361, 10034.1782708 ,  9859.70878411,
        9615.19689805,  9472.9357812 ,  9267.2233965 ,  9174.8194616 ,
        8998.50249463,  8864.82973285,  8835.5605947 ,  8650.08606761,
        8540.25855002,  8500.02283666,  8330.20689362,  8240.32509156,
        8145.98017367,  8076.10818813,  7895.15437274,  7835.46248441,
        7754.68216055,  7681.81949413,  7615.59653903,  7535.22778734,
        7507.80407245,  7341.14166959,  7284.85541612,  7175.8070408 ,
        7023.53569297,  6990.30741377,  6952.02586698,  6911.75479081,
        6837.5768249 ,  6602.45032349,  6568.63235763,  6407.80820984,
      