In [33]:
import sklearn.metrics.pairwise
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import matthews_corrcoef
import math
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import confusion_matrix
from sklearn.kernel_approximation import Nystroem, RBFSampler
import sklearn

In [43]:
data_in = pd.read_csv("./DataMatrices/class/unionMatrix_TreeBasedClassifier_Class.csv")

In [44]:
def run_svm(dataframe):
    data = dataframe.copy()
    y = np.array(data[["label"]]).ravel()
    #y[y>0] = 1
    x = data.drop(["label"], axis = 1)

    kf = StratifiedKFold(n_splits=3)
    for train_index, test_index in kf.split(x, y):
        x_train, x_test = x.iloc[train_index], x.iloc[test_index]
        y_train, y_test = y[train_index], y[test_index]

        clf = svm.SVC(kernel='rbf', C=3)
        #feature_map_nystroem = Nystroem(gamma=.2, n_components=10)
        #x_train_transformed = feature_map_nystroem.fit_transform(x_train)
        #x_test_transformed = feature_map_nystroem.fit_transform(x_test)
        #x_train_transformed = RBFSampler(gamma=1, n_components=10).fit_transform(x_train)
        clf.fit(x_train, y_train)

        print("accuracy: ", clf.score(x_test, y_test))
        print("matthews coef: ", matthews_corrcoef(y_test, clf.predict(x_test)))
        print(confusion_matrix(y_test, clf.predict(x_test)))

    #model = svm.SVC(decision_function_shape='ovr', kernel='rbf', gamma='auto')
    #return matthews_corrcoef(y_test, model.predict(x_test)), confusion_matrix(y_test, model.predict(x_test))

In [45]:
run_svm(data_in)

accuracy:  0.4732142857142857
matthews coef:  0.0683832534218572
[[114  35   0   0   0]
 [ 99  45   0   0   0]
 [ 17   6   0   0   0]
 [  9   3   0   0   0]
 [  4   4   0   0   0]]
accuracy:  0.48656716417910445
matthews coef:  0.10814933020649929
[[131  17   0   0   0]
 [113  32   0   0   0]
 [ 15   8   0   0   0]
 [ 10   1   0   0   0]
 [  4   4   0   0   0]]
accuracy:  0.4597014925373134
matthews coef:  0.04176571571951059
[[97 51  0  0  0]
 [87 57  0  0  0]
 [13 11  0  0  0]
 [ 5  6  0  0  0]
 [ 4  4  0  0  0]]


In [46]:
data_in.columns

Index(['Bacteria;Bacteroidota;Bacteroidia',
       'Bacteria;Bdellovibrionota;Bdellovibrionia',
       'Bacteria;Campilobacterota;Campylobacteria',
       'Bacteria;Dependentiae;Babeliae',
       'Bacteria;Elusimicrobiota;Elusimicrobia',
       'Bacteria;Fibrobacterota;Fibrobacteria',
       'Bacteria;Firmicutes;uncultured',
       'Bacteria;Fusobacteriota;Fusobacteriia',
       'Bacteria;Myxococcota;Polyangia', 'Bacteria;Myxococcota;bacteriap25',
       'Bacteria;Patescibacteria;Saccharimonadia',
       'Bacteria;Spirochaetota;Brachyspirae',
       'Bacteria;Acidobacteriota;Subgroup 19',
       'Bacteria;Acidobacteriota;Vicinamibacteria',
       'Bacteria;Chloroflexi;Chloroflexia',
       'Bacteria;SAR324 clade(Marine group B);uncultured delta proteobacterium',
       'label'],
      dtype='object')